application: qurantopics
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /load/.*
  script: controllers/data_loader.py
  login: admin

- url: /load_all/.*
  script: controllers/data_loader_one_step.py
  login: admin
 
- url: /topics/.*
  script: controllers/topics.py

- url: /admin/.*
  script: controllers/admin.py
  login: admin

- url: /.*
  script: controllers/qurantopics.py
