application: qurantopics-hrd
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  mime_type: text/css
  
- url: /UthmanicHafs1Ver09.otf
  static_files: static/UthmanicHafs1Ver09.otf
  upload: static/UthmanicHafs1Ver09.otf

- url: /(.*\.(png|ico))
  static_files: static/images/\1
  upload: static/images/(.*\.(png|ico))

- url: /(.*\.(js))
  static_files: static/js/\1
  upload: static/js/(.*\.(js))
  
- url: /bootstrap/(.*)
  static_files: static/bootstrap/\1
  upload: static/bootstrap/.*

- url: /load/.*
  script: controllers/data_loader.py
  login: admin

- url: /load_all/.*
  script: controllers/data_loader_one_step.py
  login: admin
 
- url: /topics/.*
  script: controllers/topics.py

- url: /admin/.*
  script: controllers/admin.py
  login: admin

- url: /.*
  script: controllers/qurantopics.py
