application: qurantopics
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /navbar.png
  static_files: static/images/navbar.png
  upload: static/images/navbar.png

- url: /navbar2.png
  static_files: static/images/navbar2.png
  upload: static/images/navbar2.png

- url: /load/.*
  script: controllers/data_loader.py
  login: admin

- url: /load_all/.*
  script: controllers/data_loader_one_step.py
  login: admin
 
- url: /topics/.*
  script: controllers/topics.py

- url: /admin/.*
  script: controllers/admin.py
  login: admin

- url: /.*
  script: controllers/qurantopics.py
